// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllDevices() {
  return window['go']['main']['App']['GetAllDevices']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsRoot() {
  return window['go']['main']['App']['IsRoot']();
}

export function StartCapture(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartCapture'](arg1, arg2, arg3);
}
