// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllDevices():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsRoot():Promise<boolean>;

export function StartCapture(arg1:string,arg2:boolean,arg3:string):Promise<void>;
